# Generated by Django 5.1.5 on 2025-03-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_anchor_site_engineer'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_data',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
